version:  '3.6'
services:
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    image: postgres:latest

    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - /Users/leilaruiz/db_data:/var/lib/postgresql/data
